language: python
python:
 - 2.7

install:
  - pip install -q dulwich mercurial==3.4 mock pygments
  - pip install . --use-mirrors

script: python managevcs/tests/__main__.py
after_script: python setup.py flakes

notifications:
    email:
        - dzhiltsov@me.com
